version: "3"
services:
    php-fpm:
        build:
            context: docker/php
        container_name: php-fpm
        volumes:
            - php_socket:/var/run/php
            - ./:/var/www/
        environment:
            COMPOSER_MEMORY_LIMIT: -1
        networks:
        - project
    nginx:
        build:
            context: docker/nginx
        container_name: nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites-available/:/etc/nginx/sites-available
            - ./docker/nginx/star.hexis.dev:/etc/nginx/star.hexis.dev
            - ./docker/logs/nginx/:/var/log/nginx/
            - php_socket:/var/run/php
        depends_on:
            - php-fpm
        networks:
        - project
        ports:
            - "80:80"
            - "443:443"
    elasticsearch:
        image: elasticsearch:7.12.1
        container_name: elasticsearch
        environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        volumes:
        - elastic:/usr/share/elasticsearch/data
        networks:
        - project
        ports:
        - 9200:9200
        - 9300:9300
    mariadb:
        image: mariadb:10.6
        container_name: mariadb
        restart: always
        environment:
        - MARIADB_ROOT_PASSWORD=example
        - MARIADB_DATABASE=praksa
        networks:
        - project
        ports:
        - "3306:3306"
    tika:
        image: apache/tika:1.26
        container_name: tika
        ports:
        - 9998:9998
        networks:
        - project

volumes:
    elastic:
        driver: local
    php_socket:
networks:
    project:
        driver: bridge
